export { default as OnboardImage1 } from './OnboardImage1'
export  { default as OnboardImage2 } from './OnboardImage2'
export  { default as OnboardImage3 } from './OnboardImage3'
export  { default as LobbyImage } from './LobbyImage'
export * from './png'