export enum routes {
    //auth
    ONBOARD = 'ONBOARD',
    SIGN_IN = 'SIGN_IN',
    CREATE_ACCOUNT = 'CREATE_ACCOUNT',
    LOBBY = 'LOBBY',
    UPDATE_PROFILE = 'UPDATE_PROFILE',

    BOTTOM_TAB = 'BOTTOM_TAB',
    HOME = 'HOME',
 
    PROFILE = 'PROFILE',
    BOOKMARK = 'BOOKMARK',
    EXPLORE = 'EXPLORE',

}
