export enum routes {
    ONBOARD = 'ONBOARD',
    SIGN_IN = 'SIGN_IN',
    CREATE_ACCOUNT = 'CREATE_ACCOUNT',

    BOTTOM_TAB = 'BOTTOM_TAB',
    HOME = 'HOME',
 
    PROFILE = 'PROFILE',
    BOOKMARK = 'BOOKMARK',
    EXPLORE = 'EXPLORE',

}
