export enum routes {
    ONBOARD = 'ONBOARD',
    ONBOARD1 = 'ONBOARD1',
    ONBOARD2 = 'ONBOARD2',
    ONBOARD3 = 'ONBOARD3',
    SIGN_IN = 'SIGN_IN',
    CREATE_ACCOUNT = 'CREATE_ACCOUNT',
    LOBBY = 'LOBBY',

    BOTTOM_TAB = 'BOTTOM_TAB',
    HOME = 'HOME',
 
    PROFILE = 'PROFILE',
    BOOKMARK = 'BOOKMARK',
    EXPLORE = 'EXPLORE',

}
